### ISSUE TITLE
:) can't visit" http://localhost:3001/login "in browser

### ISSUE THREAD

**Issue by bringtree** [Chanran/reactTodoLists#1]
I cry to visit "http://localhost:3001/login", but it returns a error "Cannot GET /login".(I guess that the router maybe have a little question.)
Could you give a hand?

**Comment by Chanran** [comment]
My fault.
README.md was wrong.  
fixed in [modify README.md](https://github.com/Chanran/reactTodoLists/commit/b5b2a8f998fe42a1856f0d5f929fb7929792a097#diff-04c6e90faac2675aa89e2176d2eec7d8)
